apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels: 
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.container.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "backend.fullname" . }}
          image: {{ .Values.backend.container.image }}
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: {{ .Values.backend.container.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: JWT_SECRET
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SMTP_PORT
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SMTP_PASSWORD
            - name: AZURE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: AZURE_ENDPOINT
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: AZURE_SAS_TOKEN
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_TEST_KEY
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: STRIPE_TEST_KEY
      imagePullSecrets:
      - name: regcred

